// 초등학생 수준 브릿지 단어 목록 (공유 글자가 없을 때 연결용)
export const ELEMENTARY_WORDS: { word: string; clue: string }[] = [
  { word: '사과', clue: '빨간 과일' },
  { word: '바나나', clue: '노란 과일' },
  { word: '하늘', clue: '파란 하늘' },
  { word: '구름', clue: '하늘에 떠 있어요' },
  { word: '바람', clue: '불어오는 공기' },
  { word: '꽃', clue: '아름다운 식물' },
  { word: '나무', clue: '숲에 많아요' },
  { word: '물', clue: '투명한 액체' },
  { word: '불', clue: '뜨겁고 밝아요' },
  { word: '땅', clue: '우리가 밟는 곳' },
  { word: '산', clue: '높고 큰 지형' },
  { word: '강', clue: '물이 흘러요' },
  { word: '바다', clue: '넓고 깊은 물' },
  { word: '학교', clue: '공부하는 곳' },
  { word: '집', clue: '사는 곳' },
  { word: '밥', clue: '쌀로 만든 음식' },
  { word: '빵', clue: '밀로 만든 음식' },
  { word: '우유', clue: '흰색 음료' },
  { word: '고양이', clue: '야옹 하는 동물' },
  { word: '강아지', clue: '멍멍 하는 동물' },
  { word: '새', clue: '날개가 있어요' },
  { word: '물고기', clue: '물속에 살아요' },
  { word: '사람', clue: '우리 모두' },
  { word: '아이', clue: '어린 사람' },
  { word: '엄마', clue: '어머니' },
  { word: '아빠', clue: '아버지' },
  { word: '친구', clue: '사이좋은 사람' },
  { word: '선생님', clue: '학교에서 가르쳐요' },
  { word: '공', clue: '둥근 놀이 도구' },
  { word: '책', clue: '읽는 것' },
  { word: '연필', clue: '쓰는 도구' },
  { word: '지우개', clue: '지우는 도구' },
  { word: '가방', clue: '들고 다녀요' },
  { word: '신발', clue: '발에 신어요' },
  { word: '옷', clue: '입는 것' },
  { word: '모자', clue: '머리에 써요' },
  { word: '시계', clue: '시간을 알아요' },
  { word: '전화', clue: '통화하는 기기' },
  { word: '버스', clue: '대중교통' },
  { word: '자동차', clue: '도로를 달려요' },
  { word: '자전거', clue: '페달을 밟아요' },
  { word: '비행기', clue: '하늘을 날아요' },
  { word: '봄', clue: '꽃이 피는 계절' },
  { word: '여름', clue: '더운 계절' },
  { word: '가을', clue: '단풍이 드는 계절' },
  { word: '겨울', clue: '눈이 오는 계절' },
  { word: '눈', clue: '하얗게 내려요' },
  { word: '비', clue: '하늘에서 내려요' },
  { word: '태양', clue: '밝고 뜨거워요' },
  { word: '달', clue: '밤에 빛나요' },
  { word: '별', clue: '밤하늘에 반짝여요' },
];
